if __name__=="__main__":
    import subprocess
    subprocess.call("main.py", shell=True)
    exit(0)

from screen import screen
import pygame
import DatenSammeln as ds
from screen import screen

def gameWin(spieler):                                                       #Codequelle: GameOver
    screen.blit(pygame.image.load("Bilder/GameWin.png"), (0, 0))
    pygame.display.update()
    pygame.time.wait(2000)
    pygame.mixer.music.stop()
    pygame.mixer.music.load("Sound/level.mp3")
    pygame.mixer.music.play(-1, 0.0)
    pygame.mixer.music.set_volume(1)
    level = 0
    ds.daten_csv(6, spieler.schritteZaehler)
    ds.daten_csv(7, spieler.schussZaehler)
    ds.write_csv()
    spieler.schritteZaehler = 0
    spieler.schussZaehler = 0
    return level